# -*- coding: utf-8 -*-
"""Trabalho Introdução à CC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18giPTkiHBGlt0DY1lOjPRA7qP0OGh37o

# Introdução à Ciência da Computação (UNIVALI), com Felipe Viel: aplicação em Python - Caio César Sabino Soares e Isis Tristão dos Santos

## Processamento de imagem em Python - detecção de bordas com o OpenCV e algoritmo Canny

Importa a biblioteca do OpenCV
"""

import cv2

"""Lê a imagem alocada no diretório abaixo"""

img = cv2.imread('/content/data/python.png',1)

"""Define alguns parâmetros de entrada e aplica o **detector de bordas Canny**"""

limiar_inferior = 30
limiar_superior = 90
tamanho_kernel = 5

img1 = cv2.Canny(img,limiar_inferior, limiar_superior, tamanho_kernel)

from google.colab import drive
drive.mount('/content/drive')

"""No Google Colab, temos que importar a *cv2_imshow* para poder exibir uma imagem, caso contrário kernel do Colab trava.



"""

from google.colab.patches import cv2_imshow


cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

"""Aplica a detecção de bordas na imagem desejada"""

from google.colab.patches import cv2_imshow

cv2_imshow(img)
cv2_imshow(img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

"""O resultado é impressionante e a aplicabilidade destas funcionalidades são extremamente amplas"""